//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HOK.MaterialGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HOK.MaterialGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap materialGenerator_32x32 {
            get {
                object obj = ResourceManager.GetObject("materialGenerator_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaterialGenerator_Command.
        /// </summary>
        internal static string MaterialGenerator_AdditionalButtonNames {
            get {
                return ResourceManager.GetString("MaterialGenerator_AdditionalButtonNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a Material Generator description..
        /// </summary>
        internal static string MaterialGenerator_Description {
            get {
                return ResourceManager.GetString("MaterialGenerator_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to materialGenerator_32x32.png.
        /// </summary>
        internal static string MaterialGenerator_ImageName {
            get {
                return ResourceManager.GetString("MaterialGenerator_ImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Generator.
        /// </summary>
        internal static string MaterialGenerator_Name {
            get {
                return ResourceManager.GetString("MaterialGenerator_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOK.MaterialGenerator.
        /// </summary>
        internal static string MaterialGenerator_Namespace {
            get {
                return ResourceManager.GetString("MaterialGenerator_Namespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials.
        /// </summary>
        internal static string MaterialGenerator_PanelName {
            get {
                return ResourceManager.GetString("MaterialGenerator_PanelName", resourceCulture);
            }
        }
    }
}
